### ISSUE TITLE
Resource not available for anonymous access

### ISSUE THREAD

**Issue by MatteGary** [touchifyapp/vsts-changed-files#22]
Hi,
I setup a simple build pipeline with two of Changed Files steps as a test.
At the first one I'm getting this error:

##[error]﻿{"$id":"1","innerException":null,"message":"TF400813: Resource not available for anonymous access. Client authentication required.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

I'm using TFS versioning, and I'm able to run a pipeline that downloads and build an entire branch.

How can I solve this?
Thanks

**Comment by SomaticIT** [comment]
This task needs a token access (`System.AccessToken`) to collect information about previous project's builds.
Please check that the System Variable `System.AccessToken` is correctly set on your pipeline.

**Comment by MatteGary** [comment]
Hi,
thanks, I also needed to check the "Allow scripts to access the OAuth token" box, now the error is different.

##[error]Unable to locate executable file: 'git'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

I'm using TFVC as source for the pipeline.
Do you know if this is solvable?
Thanks
Matteo

**Comment by SomaticIT** [comment]
Sorry for the delay.
This plugin only works with `git` as for now.
If you need `tfvc` protocol, you can contribute by submitting a PR.
Thanks
