### ISSUE TITLE
Number of files changed in a variable

### ISSUE THREAD

**Issue by bdn-mca** [touchifyapp/vsts-changed-files#31]
Do you think it is a good idea to set the number of changed files (or maybe number of changes?) as a variable which can be used in the next steps, as a way to enforce smaller pull requests in a team?

**Comment by SomaticIT** [comment]
Hello,

Why not, feel free to submit a PR.

You will need to adapt the [getChangedFiles](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/index.ts#L58) and [matchFiles](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/lib/matcher.ts#L3) functions and use the [setVariable](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/lib/util.ts#L17) utility.

Let us know if you need more information.

Thanks
