### ISSUE TITLE
where it stores changed files, the variable I find contains only true or false value. I want to copy changed files but I dont know the source

### ISSUE THREAD

**Issue by omptech** [touchifyapp/vsts-changed-files#32]
please let me know if this feature is not available

**Comment by SomaticIT** [comment]
Hello,

As for now, there is no variable containing changed files.

You can eventually use the [multiple variable configuration](https://github.com/touchifyapp/vsts-changed-files/issues/32) but I'm not sure it match your need.

If you interested in this feature, feel free to submit a PR.

You will need to adapt the [getChangedFiles](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/index.ts#L58) and [matchFiles](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/lib/matcher.ts#L3) functions and use the [setVariable](https://github.com/touchifyapp/vsts-changed-files/blob/f5e2d56434d69842c00363d462c6d83fe2e19a60/changed-files/lib/util.ts#L17) utility.

Do not hesitate to ask for help.

Thanks
