### ISSUE TITLE
No change detected in case of multibranch

### ISSUE THREAD

**Issue by ladlavj** [touchifyapp/vsts-changed-files#33]
It used to work before and stopped suddenly, not sure what changed.
I doubt the Azure pipeline job checkout behavior has changed, the checked out code in working directory has no branch with names
```
# git branch -a
* (HEAD detached at origin/13777ee2210bbcca0c61686a7e1270216619eb09)
  remotes/origin/13777ee2210bbcca0c61686a7e1270216619eb09
```

### Job output
```
Reference Branch: main
Current Branch: refs/pull/177/merge
> Comparing 'refs/pull/177/merge' with the reference branch 'main'...
> Executing: git diff --name-only origin/main...
fatal: ambiguous argument 'origin/main...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/usr/bin/git diff --name-only origin/main...
>> No change found since last succeeded build!
>> CODECHANGED: No change detected since last succeeded build, setting "codeChanged" to "false"
```

It works when added the `checkout` step with `fetchDepth: 0` option

**Comment by SomaticIT** [comment]
Hello,

Indeed, the `checkout` used to default `fetchDepth` to `0`.
Maybe it's not the case when working on PR.

Unfortunately, this module does not have access to the remote repository.

I added a note in the **[README](https://github.com/touchifyapp/vsts-changed-files/blob/master/README.md#troubleshooting) to** inform users of the process to adopt in your case.

Thanks
