### ISSUE TITLE
HasChanged is always true

### ISSUE THREAD

**Issue by goors** [touchifyapp/vsts-changed-files#41]
First of all thanks for stuff that you did.

I am always getting true with message:

Changes detected since last succeeded build, setting `"CodeChanged"` to `"true"`

In list of file, it says all files are changed.

What do you mean by since last succeeded build?

Is there a way to have this part work for just only one file:

```
rules: |
   [CodeChanged]
   src/**/*.ts
```

I have 20 crawlers, and if i only change one file, i do not want for all them to go to build, and release and so on.

So something like:

r`ules: src/Crawlers/CrawlernumberOne.ts`

**Comment by SomaticIT** [comment]
Hello,

Thank you for your message.

If I understand correctly, you can use the multi-variable usage:
https://github.com/touchifyapp/vsts-changed-files#multi-variable-usage.

```yaml
rules: |
   [CrawlerNumberOne]
   src/Crawlers/CrawlerNumberOne.ts

   [CrawlerNumberTwo]
   src/Crawlers/CrawlerNumberTwo.ts

   [CrawlerNumberThree]
   src/Crawlers/CrawlerNumberThree.ts

  ...
```

Does this works for you?

Thanks

**Comment by goors** [comment]
Thanks. That is THE thing. Thank you.
